# Generated by Django 2.1.7 on 2019-03-16 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('account', models.CharField(choices=[('现金', '现金'), ('银行卡', '银行卡'), ('支付宝', '支付宝')], max_length=4)),
                ('outcometype', models.CharField(choices=[('服饰', '服饰'), ('食品酒水', '食品酒水'), ('居家物业', '居家物业'), ('行车交通', '行车交通'), ('文化教育', '文化教育'), ('休闲娱乐', '休闲娱乐')], max_length=4)),
                ('people', models.CharField(choices=[('自己', '自己'), ('家人', '家人'), ('其他人', '其他人')], default='自己', max_length=4)),
                ('money', models.DecimalField(decimal_places=1, max_digits=20)),
                ('description', models.TextField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('account', models.CharField(choices=[('现金', '现金'), ('银行卡', '银行卡'), ('支付宝', '支付宝')], max_length=4)),
                ('incometype', models.CharField(choices=[('工资', '工资'), ('奖金补贴', '奖金补贴'), ('投资分红', '投资分红'), ('其他', '其他')], max_length=4)),
                ('people', models.CharField(choices=[('自己', '自己'), ('家人', '家人'), ('其他人', '其他人')], default='自己', max_length=4)),
                ('money', models.DecimalField(decimal_places=1, max_digits=20)),
                ('description', models.TextField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
