# Generated by Django 2.1.7 on 2019-03-16 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountsystem', '0003_auto_20190316_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='username',
            field=models.ForeignKey(default='lyj', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
