# Generated by Django 2.1.7 on 2019-04-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsystem', '0004_auto_20190316_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expend',
            name='money',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='money',
            field=models.FloatField(max_length=20),
        ),
    ]
