# Generated by Django 2.1.7 on 2019-04-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountsystem', '0005_auto_20190403_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='try', max_length=8)),
                ('member_relation', models.CharField(choices=[('夫妻', '夫妻'), ('父子', '父子'), ('母子', '母女')], max_length=4)),
                ('member_password', models.CharField(default='111111', help_text='成员密码，默认为111111', max_length=20)),
                ('description', models.TextField(null=True)),
                ('username', models.ForeignKey(default='lyj', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
