# Generated by Django 2.1.7 on 2019-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsystem', '0006_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_relation',
            field=models.CharField(choices=[('夫妻', '夫妻'), ('父子', '父子'), ('母子', '母女'), ('兄弟姐妹', '兄弟姐妹')], max_length=4),
        ),
    ]
